I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapter-2.rpy", line 22, in script
    b "What the HELL are you wearing?"
Exception: Sayer 'b' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chapter-2.rpy", line 22, in script
    b "What the HELL are you wearing?"
  File "renpy/ast.py", line 680, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'b' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.2.1292
Time Travel Game V01 1.0
Sat Apr  3 19:32:25 2021
