I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapter-1.rpy", line 105, in script
    s "What is this?? Hm...maybe it's from the boss. Guess I'll drop it off."
Exception: Sayer 's' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chapter-1.rpy", line 105, in script
    s "What is this?? Hm...maybe it's from the boss. Guess I'll drop it off."
  File "/Applications/renpy-7.4.2-sdk/renpy/ast.py", line 680, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Applications/renpy-7.4.2-sdk/renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 's' is not defined.

Darwin-20.3.0-x86_64-i386-64bit
Ren'Py 7.4.2.1292
Time Travel Game V01 1.0
Sat Mar 27 17:55:36 2021
